### ISSUE TITLE
General error

### ISSUE THREAD

**Issue by monkeyboy107** [saschpe/godaddy-dyndns#6]
After I ran the shell script this came up
"godaddy-dyndns.sh: line 11: .venv/bin/activate: No such file or directory
Requirement already up-to-date: pif in /home/minecraft/.local/lib/python2.7/site-packages
Collecting pygodaddy from git+git://github.com/saschpe/pygodaddy.git#egg=pygodaddy
  Cloning git://github.com/saschpe/pygodaddy.git to /tmp/pip-build-XfUW_c/pygodaddy
Collecting argparse (from pif)
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Requirement already up-to-date: requests>=1.2.3 in /home/minecraft/.local/lib/python2.7/site-packages (from pif)
Requirement already up-to-date: tldextract>=1.5.1 in /home/minecraft/.local/lib/python2.7/site-packages (from pygodaddy)
Requirement already up-to-date: idna in /home/minecraft/.local/lib/python2.7/site-packages (from tldextract>=1.5.1->pygodaddy)
Requirement already up-to-date: setuptools in /home/minecraft/.local/lib/python2.7/site-packages (from tldextract>=1.5.1->pygodaddy)
Requirement already up-to-date: requests-file>=1.4 in /home/minecraft/.local/lib/python2.7/site-packages (from tldextract>=1.5.1->pygodaddy)
Requirement already up-to-date: six in /home/minecraft/.local/lib/python2.7/site-packages (from requests-file>=1.4->tldextract>=1.5.1->pygodaddy)
Installing collected packages: pygodaddy, argparse
  Found existing installation: pygodaddy 0.2.2
    Uninstalling pygodaddy-0.2.2:
Exception:
Traceback (most recent call last):
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/minecraft/.local/lib/python2.7/site-packages/pip/utils/**init**.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pygodaddy-0.2.2-py2.7.egg-info/installed-files.txt'
Traceback (most recent call last):
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "godaddy-dyndns.py", line 19, in <module>
    config.get('godaddy', 'password'))
  File "/home/minecraft/.local/lib/python3.5/site-packages/pygodaddy/client.py", line 99, in login
    r = self.session.get(self.default_url)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, *_kwargs)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/minecraft/.local/lib/python3.5/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
godaddy-dyndns.sh: line 14: deactivate: command not found"

**Comment by AndreasLoow** [comment]
It has been broken for a while, see e.g #4. In case you're interested, I have a working fork at AndreasLoow/godaddy-dyndns.
